src/main/java/com/corenetworks/profesores/blog/beans/LoginBean.java
package com.corenetworks.profesores.blog.beans;

public class LoginBean {
	private String email;
	private String password;

	public LoginBean() {
		super();
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

src/main/java/com/corenetworks/profesores/blog/beans/RegisterBean.java
package com.corenetworks.profesores.blog.beans;

import java.util.Date;

public class RegisterBean {
	private String nombre;
	private String email;
	private Date fechaAlta;
	private String ciudad;
	private String password;
	private String secondPassword;

	public RegisterBean() {
		super();
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getFechaAlta() {
		return fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	public String getCiudad() {
		return ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSecondPassword() {
		return secondPassword;
	}

	public void setSecondPassword(String secondPassword) {
		this.secondPassword = secondPassword;
	}
	
	

}

src/main/java/com/corenetworks/profesores/blog/model/Pregunta.java
package com.corenetworks.profesores.blog.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

//import org.hibernate.annotations.ColumnTransformer;
import org.hibernate.annotations.CreationTimestamp;

@Entity
@Table(name="pregunta")
public class Pregunta {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private long id;
	
	@Column
	private String titulo;
	
	
	@Column
	@Lob
	private String contenido;
	
	@Column
	@CreationTimestamp
	private Date fecha;
		
	@ManyToOne
	private Profesor profesor;
    
	@OneToMany(mappedBy="pregunta")
	private List<Respuesta> respuestas = new ArrayList<>();
	
	public Pregunta() {
		super();
	}

	public Pregunta(String url, String titulo, String contenido, Profesor profesor) {
		super();
		this.titulo = titulo;
		this.contenido = contenido;
		this.profesor = profesor;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getContenido() {
		return contenido;
	}

	public void setContenido(String contenido) {
		this.contenido = contenido;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Profesor getProfesor() {
		return profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public List<Respuesta> getRespuesta() {
		return respuestas;
	}

	public void setRespuesta(List<Respuesta> respuestas) {
		this.respuestas = respuestas;
	}
	
	
    
}

src/main/java/com/corenetworks/profesores/blog/controller/LoginController.java
package com.corenetworks.profesores.blog.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.corenetworks.profesores.blog.beans.LoginBean;
import com.corenetworks.profesores.blog.dao.ProfesorDao;
import com.corenetworks.profesores.blog.model.Profesor;

@Controller
public class LoginController {
	@Autowired
	private ProfesorDao profesorDao;
	
	@Autowired
	private HttpSession httpSession;

	@GetMapping(value = "/signin")
	public String showForm(Model model) {
		model.addAttribute("profesorLogin", new LoginBean());
		return "login";
	}

	@PostMapping(value = "/login")
	public String submit(@ModelAttribute("profesorLogin") LoginBean loginBean, Model model) {
		// userDao.create(new User(r.getNombre(), r.getEmail(), r.getCiudad(),
		// r.getPassword()));
		Profesor u = profesorDao.getByEmailAndPassword(loginBean.getEmail(), loginBean.getPassword());
		if (u != null) {
			httpSession.setAttribute("profesorLoggedIn", u);
			
		    return "redirect:/";
		} else {
			model.addAttribute("error","Error de validación");
			return "login";
		}
	}
	
	
	@GetMapping(value = "/logout")
	public String logout(Model model) {
		httpSession.removeAttribute("profesorLoggedIn");
		return "redirect:/";
	}
}

src/main/java/com/corenetworks/profesores/blog/controller/RegisterController.java
package com.corenetworks.profesores.blog.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.corenetworks.profesores.blog.beans.RegisterBean;
import com.corenetworks.profesores.blog.dao.ProfesorDao;
import com.corenetworks.profesores.blog.model.Profesor;

@Controller
public class RegisterController {
	@Autowired
	private ProfesorDao profesorDao;

	@GetMapping(value = "/signup")
	public String showForm(Model model) {
		model.addAttribute("profesorRegister", new RegisterBean());
		return "register";
	}

	@PostMapping(value = "/register")
	public String submit(@ModelAttribute("profesorRegister") RegisterBean r, Model model) {
		profesorDao.create(new Profesor(r.getNombre(), r.getEmail(), r.getCiudad(), r.getPassword()));

		return "redirect:/autores";
	}
}

src/main/webapp/WEB-INF/jsp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" session="true" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c"  %>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix = "fn"  uri = "http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>   
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="author" content="Core Netowkrs Sevilla">
<meta name="description" content="Blog creado con Spring Boot, Spring MVC, JPA e Hibernate">

<title>App Preguntas</title>

<link href="webjars/bootstrap/3.3.7-1/css/bootstrap.min.css"  rel="stylesheet">
<link href="assets/css/jumbotron-narrow.css"  rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="header clearfix">
	    <nav>
	       <ul  class="nav nav-pills pull-right">
		       <c:choose>
		         <c:when test="${not empty sessionScope.profesorLoggedIn }">
		            <jsp:include page="includes/menu_logged.jsp">
		            <jsp:param value="inicio" name="inicio"/>
		            <jsp:param name="usuario" value="${sessionScope.profesorLoggedIn.nombre }"/>
		            
		          </jsp:include>
		         </c:when>
		         <c:otherwise>
		          <jsp:include page="includes/menu.jsp">
		            <jsp:param value="inicio" name="inicio"/>
		          </jsp:include>
		         </c:otherwise> 
		       </c:choose>   
	       </ul>
	       
	    </nav>
	    <h3 class="text-muted">App Preguntas</h3>
    
    </div>
    
 	    <div class="jumbotron">
          <h1>App de Preguntas</h1>
          <p>Preguntas y Respuestas.</p>
          <c:if test="${empty sessionScope.userLoggedIn }">
               <p><a href="/signup"  role="button"  class="btn btn-lg btn-success ">Regístrate</a></p>
		  </c:if>
        </div>   

		
		<c:forEach items="${listaPregunta}" var="preguntaItem">
		<div class="row">
			<div class="col-md-12 col-lg-12">
				<h1><a href="/post/${preguntaItem.id}">${preguntaItem.titulo}</a></h1>
				<div>
					<div class="pull-right" style="padding: 10px 0 0 5px;">${preguntaItem.profesor.nombre}</div>
					<img alt="User Pic" src="http://i.pravatar.cc/50?u=${preguntaItem.profesor.email}"
						class="img-circle img-responsive pull-right">
					<p></p>
				</div>
				<div style="clear: both; margin-bottom: 10px;"></div>
					<c:if test="${not empty postItem.url}">
						<p><a href="${preguntaItem.url}">${preguntaItem.url}</a></p>
					</c:if>
					<div class="dotdotdot">
						<p>${preguntaItem.contenido}</p>				
					</div>
				<div>
					<span class="badge">Escrito el <fmt:formatDate pattern="dd/MM/yyyy" value="${preguntaItem.fecha}" /> a las 
					<fmt:formatDate pattern="HH:mm:ss" value="${preguntaItem.fecha}" /></span>
					<span class="label label-info">					
                        ${(fn:length(preguntaItem.respuesta) gt 0) ? fn:length(preguntaItem.respuesta) : 'Sin '} 
						${(fn:length(preguntaItem.respuesta) == 1) ? 'respuesta' : 'respuesta'} 					
						</span>
				</div>
				<hr>
			</div>
		</div>
		</c:forEach>

        
  
  
  </div>
  
  
  <script src="webjars/jquery/3.1.1/jquery.min.js"></script> 
  <script src="webjars/bootstrap/3.3.7-1/js/bootstrap.min.js"></script>
   <script src="assets/js/jquery.dotdotdot.min.js"> </script>
    <script>
 jQuery(document).ready(function() {

   $(".dotdotdot").dotdotdot({
      height:150
   });

}); 

 </script>

  
</body>
</html>

src/main/webapp/WEB-INF/jsp/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" session="true" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c"  %>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix = "fn"  uri = "http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>   
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="author" content="Core Netowkrs Sevilla">
<meta name="description" content="Blog creado con Spring Boot, Spring MVC, JPA e Hibernate">

<title>App Preguntas</title>

<link href="webjars/bootstrap/3.3.7-1/css/bootstrap.min.css"  rel="stylesheet">
<link href="assets/css/jumbotron-narrow.css"  rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="header clearfix">
	    <nav>
	     <ul  class="nav nav-pills pull-right">
		       <c:choose>
		         <c:when test="${not empty sessionScope.profesorLoggedIn }">
		            <jsp:include page="includes/menu_logged.jsp">
		            <jsp:param value="login" name="login"/>
		            <jsp:param name="usuario" value="${sessionScope.profesorLoggedIn.nombre }"/>
		            
		          </jsp:include>
		         </c:when>
		         <c:otherwise>
		          <jsp:include page="includes/menu.jsp">
		            <jsp:param value="login" name="login"/>
		          </jsp:include>
		         </c:otherwise> 
		       </c:choose>   
		       </ul>    
	    </nav>
	    <h3 class="text-muted">App Preguntas</h3>
    
    </div>
    <div class="row">
    
	    <div class="col-lg-8 col-lg-offset-2" >
	    
	       <div class="text-center">
	          <h3>Entrar</h3>
	          <form:form id="login-form"  action="/login" method="post" role="form" 
	             modelAttribute="profesorLogin"
	          >
	           <div class="form-group">
	              <form:input type="email" name="email" id="email" tabIndex="1" class="form-control"   path="email" placeholder="Email" required="required"
	                     autofocus="autofocus" />
	           </div>
	           <div class="form-group">
	              <form:input type="password" name="password" id="password" tabIndex="2" class="form-control"   path="password" placeholder="Password"  required="required" />
	           </div>
	            <div class="form-group">
	              <button type="submit" name="login-submit" id="login-submit" tabIndex="3" class="btn btn-lg btn-primary btn-block" >Login</button>               
	           </div>          
	          </form:form>
	       </div>    
	    </div>
    </div>
    
      <c:if test="${not empty error}">
    <div class="row">
    
	      <div class="col-lg-8 col-lg-offset-2" >
	         <div class="alert alert-danger alert-dismissible fade in" role="alert">
	         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	         <!--  Esto hace que se muestre una X en la zona de error  -->
	         <%  
	                // Esto hace que se muestre una X en la zona de error  %>
	          <%    /* Esto hace que se muestre una X en la zona de error 
	                        Varias líneas
	          
	                 */%>
	         
	            <span aria-hidden="true">&times;</span>
	         </button>
                 <c:out value="${error}"></c:out>
              </div>
         </div>
       </div>  
      </c:if>
    <footer class="footer">
        
      
    </footer>

  
  
  </div>
  
  
  <script src="webjars/jquery/3.1.1/jquery.min.js"></script> 
  <script src="webjars/bootstrap/3.3.7-1/js/bootstrap.min.js"></script>
  <script src="assets/js/jquery.validate.min.js"></script>
  <script src="assets/js/messages_es.js"></script>
  <script>
    $(document).ready(function() { 
              $("#register-form").validate();
         }
     );
     
  </script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/preguntadetail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">

<title>App Preguntas</title>

<!-- Bootstrap core CSS -->
<link href="/webjars/bootstrap/3.3.7-1/css/bootstrap.min.css"
	rel="stylesheet">


<!-- Custom styles for this template -->

<link href="<c:url value="/assets/css/jumbotron-narrow.css" />"
	rel="stylesheet">


<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    
</head>

<body>

	<div class="container">
		<div class="header clearfix">
			<nav>
				<ul class="nav nav-pills pull-right">
					<c:choose>
						<c:when test="${not empty sessionScope.profesorLoggedIn}">
							<jsp:include page="includes/menu_logged.jsp" flush="true">
								<jsp:param name="inicio" value="inicio" />
								<jsp:param name="usuario"
									value="${sessionScope.profesorLoggedIn.nombre}" />
							</jsp:include>

						</c:when>
						<c:otherwise>
							<jsp:include page="includes/menu.jsp">
								<jsp:param name="otro" value="otro" />
							</jsp:include>
						</c:otherwise>
					</c:choose>
				</ul>
			</nav>
			<h3 class="text-muted">App Preguntas</h3>
		</div>

		<div class="row">
			<div class="col-md-12 col-lg-12">
				<h1>${pregunta.titulo}</h1>
				<div>
					<div class="pull-right" style="padding: 10px 0 0 5px;">${pregunta.profesor.nombre}</div>
					<img alt="User Pic"
						src="http://i.pravatar.cc/50?u=${pregunta.profesor.email}"
						class="img-circle img-responsive pull-right">
					<p></p>
				</div>
				<div style="clear: both; margin-bottom: 10px;"></div>
				<p>${pregunta.contenido}</p>
				<div>
					<span class="badge">Escrito el <fmt:formatDate
							pattern="dd/MM/yyyy" value="${pregunta.fecha}" /> a las <fmt:formatDate
							pattern="HH:mm:ss" value="${pregunta.fecha}" /></span>
				</div>
				<hr>
			</div>
		</div>

		
		<div class="row comment">
			<div class="col-md-12 col-lg-12">
				<div class="well">
					
					<h4>¿Quieres responder?</h4>
					<c:choose>
					<c:when test="${not empty sessionScope.profesorLoggedIn}">	
									
						<form:form method="POST" modelAttribute="respuestaForm" id="form-comment"  action="/submit/newrespuesta" role="form" >
							<form:input type="hidden" id="pregunta_id" name="post_id" path="pregunta_id" value="${pregunta.id}" />
							<div class="input-group">					
							<form:input type="text" class="form-control input-sm chat-input"
								placeholder="Escribe tu respuesta aquí" path="contenido" /> 
							<span class="input-group-btn" id="comment-button"> 
								<a href="#" class="btn btn-primary btn-sm">
									<span class="glyphicon glyphicon-comment"></span> Responder
								</a>
							</span>
							</div>
						</form:form>
						
					</c:when>
					<c:otherwise>
						<h5>Necesita iniciar sesión para responder preguntas</h5>
					</c:otherwise>
					</c:choose>
					<hr data-brackets-id="12673">
					<ul data-brackets-id="12674" id="sortable"
						class="list-unstyled ui-sortable">		
									
						<c:if test="${not empty pregunta.respuestas }">
							<c:forEach items="${pregunta.respuestas}" var="comment">
							<li class="ui-state-default">
								<strong class="pull-left primary-font">${respuesta.profesor.nombre}</strong>
								<small class="pull-right text-muted"> 
									<span class="glyphicon glyphicon-time"></span>
									<fmt:formatDate pattern="dd/MM/yyyy" value="${respuesta.fecha}" /> a las 
									<fmt:formatDate pattern="H:m:s" value="${respuesta.fecha}" />
								</small>
								<br/>
								${respuesta.contenido}
								<br/>
							</li>						
							</c:forEach>
						</c:if>
						
					</ul>
				</div>
			</div>
		</div>

			<footer class="footer"> </footer>

		</div>
		<!-- /container -->
		<script src="/webjars/jquery/3.1.1/jquery.min.js"></script>
		<script src="/webjars/bootstrap/3.3.7-1/js/bootstrap.min.js"></script>
		<script>
		$(document).ready(function() {
		    $("#comment-button").click(function() {
				$("#form-comment").submit();
		    });
		});
		
		</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/register.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" session="true" %>
<%@ taglib uri = "http://java.sun.com/jsp/jstl/core" prefix = "c"  %>
<%@ taglib prefix = "fmt" uri = "http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix = "fn"  uri = "http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>   
    
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="author" content="Core Netowkrs Sevilla">
<meta name="description" content="Blog creado con Spring Boot, Spring MVC, JPA e Hibernate">

<title>App Preguntas</title>

<link href="webjars/bootstrap/3.3.7-1/css/bootstrap.min.css"  rel="stylesheet">
<link href="assets/css/jumbotron-narrow.css"  rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="header clearfix">
	    <nav>
	     <ul  class="nav nav-pills pull-right">
		       <c:choose>
		         <c:when test="${not empty sessionScope.userLoggedIn }">
		            <jsp:include page="includes/menu_logged.jsp">
		            <jsp:param value="inicio" name="inicio"/>
		            <jsp:param name="usuario" value="${sessionScope.userLoggedIn.nombre }"/>
		            
		          </jsp:include>
		         </c:when>
		         <c:otherwise>
		          <jsp:include page="includes/menu.jsp">
		            <jsp:param value="inicio" name="inicio"/>
		          </jsp:include>
		         </c:otherwise> 
		       </c:choose>  
	       </ul>
	    </nav>
	    <h3 class="text-muted">App Preguntas</h3>
    
    </div>
    
    <div class="col-lg-8 col-lg-offset-2" >
    
       <div class="text-center">
          <h3>Registro</h3>
          <form:form id="register-form"  action="/register" method="post" role="form" 
            autocomplete="off" modelAttribute="profesorRegister"
          >
           <div class="form-group">
              <form:input type="text" name="nombre" id="nombre" tabIndex="1" class="form-control"   path="nombre" placeholder="Nombre"/>
           </div>
           <div class="form-group">
              <form:input type="text" name="cuidad" id="ciudad" tabIndex="2" class="form-control"   path="ciudad" placeholder="Cuidad, País" />
           </div>
           <div class="form-group">
              <form:input type="email" name="email" id="email" tabIndex="3" class="form-control"   path="email" placeholder="Email" />
           </div>
           <div class="form-group">
              <form:input type="password" name="password" id="password" tabIndex="4" class="form-control"   path="password" placeholder="Password" />
           </div>
           <div class="form-group">
              <input type="password" name="confirm-password" id="confirm-password" tabIndex="5" class="form-control"  placeholder="Repetir Password"
                 data-rule-equalTo="#password"  /> 
              
           </div>          
            <div class="form-group">
              <input type="submit" name="register-submit" id="register-submit" tabIndex="6" class="form-control btn btn-info"  value="Registrar ahora" /> 
              
           </div>          
          </form:form>
       </div>
    
    
    </div>

  
  
  </div>
  
  
  <script src="webjars/jquery/3.1.1/jquery.min.js"></script> 
  <script src="webjars/bootstrap/3.3.7-1/js/bootstrap.min.js"></script>
  <script src="assets/js/jquery.validate.min.js"></script>
  <script src="assets/js/messages_es.js"></script>
  <script>
    $(document).ready(function() { 
              $("#register-form").validate();
         }
     );
     
  </script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/submit.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">

<title>App Preguntas</title>

<!-- Bootstrap core CSS -->
<link href="webjars/bootstrap/3.3.7-1/css/bootstrap.min.css"
	rel="stylesheet">


<!-- Custom styles for this template -->

<link href="<c:url value="/assets/css/jumbotron-narrow.css" />"
	rel="stylesheet">
<link href="<c:url value="/assets/css/submitform.css" />"
	rel="stylesheet">

<link href="<c:url value="/assets/wysiwyg/bootstrap3-wysihtml5.min.css" />"
	rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

	<div class="container">
		<div class="header clearfix">
			<nav>
				<ul class="nav nav-pills pull-right">
					<!-- <li role="presentation" class="active"><a href="#">Home</a></li>
					<li role="presentation"><a href="#">About</a></li>
					<li role="presentation"><a href="/autores">Autores</a></li>-->
					<c:choose>
						<c:when test="${not empty sessionScope.userLoggedIn}">
							<jsp:include page="includes/menu_logged.jsp" flush="true">
								<jsp:param name="submit" value="submit" />
								<jsp:param name="usuario" value="${sessionScope.userLoggedIn.nombre}" />
							</jsp:include>

						</c:when>
						
						<c:otherwise>
							<jsp:include page="includes/menu.jsp">
								<jsp:param name="submit" value="submit" />
							</jsp:include>
						</c:otherwise>
					</c:choose>
				</ul>
			</nav>
			<h3 class="text-muted">App Preguntas</h3>
		</div>

		<div class="row">
			<form:form method="POST" modelAttribute="post"  action="/submit/newpregunta" role="form" id="contact-form" class="contact-form">
				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<form:input type="text" class="form-control" name="title"
								autocomplete="off" id="title" placeholder="Título" path="titulo" />
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<form:input type="url" class="form-control" name="url"
								autocomplete="off" id="url" placeholder="URL (opcional)" path="url" />
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div class="form-group">
							<form:textarea class="form-control textarea" rows="3" name="text"
								id="texto" placeholder="Contenido" path="contenido"></form:textarea>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<button type="submit" class="btn main-btn pull-right">Enviar Pregunta</button>
					</div>
				</div>
			</form:form>
		</div>

		<footer class="footer"> </footer>

	</div>
	<!-- /container -->
	<script src="webjars/jquery/3.1.1/jquery.min.js"></script>
	<script src="webjars/bootstrap/3.3.7-1/js/bootstrap.min.js"></script>
	<script src="<c:url value="/assets/wysiwyg/bootstrap3-wysihtml5.all.min.js" />"></script>
	<script>
		$(document).ready(function() {
			$("#texto").wysihtml5();
		});
	
	</script>

</body>
</html>